version: "3"

services:
  app:
    build: .
    command: >
      bash -c "npm run dev"
    volumes:
    - "./:/usr/src/app"
    depends_on:
      - postgres
    ports:
      - "9000:9000"
  postgres:
    image: postgres:10.5
